export const REFACTORING_CATEGORIES = {
  "Basic Refactorings": [
    "Rename Variable",
    "Rename Field",
    "Remove Dead Code",
    "Replace Magic Literal",
  ],
  "Composing Methods": [
    "Extract Function",
    "Inline Function",
    "Extract Variable",
    "Inline Variable",
    "Combine Functions into Class",
    "Combine Functions into Transform",
    "Split Phase",
    "Slide Statements",
    "Split Loop",
    "Replace Loop with Pipeline",
    "Replace Derived Variable with Query",
    "Split Variable",
    "Move Statements into Function",
    "Move Statements to Callers",
    "Replace Inline Code with Function Call",
    "Replace Temp with Query",
    "Replace Function with Command",
    "Replace Command with Function",
    "Return Modified Value",
    "Substitute Algorithm",
  ],
  Encapsulation: [
    "Encapsulate Variable",
    "Hide Delegate",
    "Remove Middle Man",
    "Encapsulate Collection",
    "Encapsulate Record",
    "Remove Setting Method",
  ],
  "Moving Features": ["Move Function", "Move Field", "Extract Class", "Inline Class"],
  "Organizing Data": [
    "Replace Primitive with Object",
    "Change Reference to Value",
    "Change Value to Reference",
  ],
  "Simplifying Conditional Logic": [
    "Decompose Conditional",
    "Consolidate Conditional Expression",
    "Replace Nested Conditional with Guard Clauses",
    "Replace Conditional with Polymorphism",
    "Introduce Special Case",
    "Replace Control Flag with Break",
  ],
  "Refactoring APIs": [
    "Change Function Declaration",
    "Introduce Parameter Object",
    "Introduce Assertion",
    "Separate Query from Modifier",
    "Parameterize Function",
    "Remove Flag Argument",
    "Preserve Whole Object",
    "Replace Parameter with Query",
    "Replace Query with Parameter",
    "Replace Constructor with Factory Function",
    "Replace Error Code with Exception",
    "Replace Exception with Precheck",
  ],
  "Dealing with Inheritance": [
    "Pull Up Method",
    "Push Down Method",
    "Replace Type Code with Subclasses",
    "Extract Superclass",
    "Collapse Hierarchy",
    "Replace Subclass with Delegate",
    "Pull Up Constructor Body",
    "Pull Up Field",
    "Push Down Field",
    "Remove Subclass",
    "Replace Superclass with Delegate",
  ],
} as const satisfies Record<string, readonly string[]>;
