export const REFACTORING_CATEGORIES = {
  "Composing Methods": [
    "Extract Function",
    "Inline Function",
    "Extract Variable",
    "Inline Variable",
    "Change Function Declaration",
    "Rename Variable",
    "Introduce Parameter Object",
    "Combine Functions into Class",
    "Combine Functions into Transform",
    "Split Phase",
  ],
  Encapsulation: [
    "Encapsulate Variable",
    "Extract Class",
    "Replace Primitive with Object",
    "Hide Delegate",
    "Remove Middle Man",
  ],
  "Moving Features": [
    "Move Function",
    "Move Field",
    "Slide Statements",
    "Split Loop",
    "Replace Loop with Pipeline",
    "Remove Dead Code",
  ],
  "Organizing Data": ["Split Variable", "Rename Field", "Replace Derived Variable with Query"],
  "Simplifying Conditional Logic": [
    "Decompose Conditional",
    "Consolidate Conditional Expression",
    "Replace Nested Conditional with Guard Clauses",
    "Replace Conditional with Polymorphism",
    "Introduce Special Case",
    "Introduce Assertion",
  ],
  "Refactoring APIs": [
    "Separate Query from Modifier",
    "Parameterize Function",
    "Remove Flag Argument",
    "Preserve Whole Object",
    "Replace Parameter with Query",
    "Replace Constructor with Factory Function",
  ],
  Inheritance: [
    "Pull Up Method",
    "Push Down Method",
    "Replace Type Code with Subclasses",
    "Extract Superclass",
    "Collapse Hierarchy",
    "Replace Subclass with Delegate",
  ],
} as const satisfies Record<string, readonly string[]>;
